let suggestions = [
    "Os Mercenários",
    "Gigantes de aço",
    "Velozes e Furiosos 5",
    "Velozes e Furiosos 6",
    "Velozes e Furiosos 7",
    "Velozes e Furiosos 10",
    "Top Gun - Ases Indomáveis",
    "O Guarda Costas",
    "Karate Kid",
    "Era uma vez um Gênio",
    "Uma Noite no Museu",
    "Construindo uma Carreira",
    "Sempre ao Seu Lado",
    "Matilda",
    "Familia Buscapé",
    "Homem Aranha 2",
    "À Prova de Fogo",
    "Desafiando Gigantes",
    "Dupla Explosiva",
    "Triplo X",
    "Minha Mãe é uma Peça",
    "O Pequeno Nicolau",
    "Minha Mãe é uma Peça",
    "A Sogra Perfeita",
    "Top Gun: Maverick",
    "O Casamento dos Trapalhões",
    "Alice no Pais das Maravilhas",
    "O Grande Assalto",
    "O Mentiroso",
    "A Procura da Felicidade",
    "Redline: Velocidade sem Limites",
    "Transformers - O Filme",
    "O Jardim Secreto (filme)",
    "Bumblebee",
    "Carga Explosiva 3",
    "Guardiões da Galáxia 3",
    "Riquinho",
    "Free Willy",
    "Alice no Pais das Maravilhas",
    "Esqueceram de Mim",
];